In [1]:
import pandas as pd
import requests
from tqdm.notebook import tqdm

In [2]:
PATH_TO_DATASETS = "../Datasets/"

# GREEN SPACES

This dataset describes an overview of public green, except for solitary trees. This data collection includes location, type of vegetation, and management information.

In [3]:
df = pd.read_csv(f'{PATH_TO_DATASETS}openbaar-groen0.csv', sep=';')

In [28]:
df[['LAT', 'LON']] = df['geo_point_2d'].str.split(',', expand=True)
df['LAT'] = pd.to_numeric(df['LAT'], errors='coerce')
df['LON'] = pd.to_numeric(df['LON'], errors='coerce')

In [ ]:
#df.to_csv(f'{PATH_TO_DATASETS}green-spaces.csv', index=False)

In [32]:
df = pd.read_csv(f'{PATH_TO_DATASETS}green-spaces.csv')

In [33]:
df.drop(columns=['geo_point_2d', 'geo_shape', 'TECHN_KWAL', 'STREET'], inplace=True)

In [ ]:
#df.to_csv(f'{PATH_TO_DATASETS}green-spaces.csv', index=False)

# AIR POLLUTION

In [12]:
df = pd.read_csv(f'{PATH_TO_DATASETS}Raw Datasets/merged_air_pollution_data.csv')

In [16]:
df

,Sensor,Time_UTC,Time_Local,Lat,Lon,PM1,PM2.5,PM10,NO2
0,I02,2021-01-01 00:00:00,2021-01-01 01:00:00,"51,4379","5,3582","27,78","33,11","37,81",24.0
1,I02,2021-01-02 00:00:00,2021-01-02 01:00:00,"51,4379","5,3582","31,84","45,09","51,59",19.0
2,I02,2021-01-03 00:00:00,2021-01-03 01:00:00,"51,4379","5,3582","23,72","34,22","38,46",13.0
3,I02,2021-01-04 00:00:00,2021-01-04 01:00:00,"51,4379","5,3582","5,35","5,97","7,94",9.0
4,I02,2021-01-05 00:00:00,2021-01-05 01:00:00,"51,4379","5,3581","21,11","23,40","24,02",10.0
...,...,...,...,...,...,...,...,...,...
68735,NaN,2025-03-16 00:00:00,2025-03-16 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68736,NaN,2025-03-17 00:00:00,2025-03-17 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68737,NaN,2025-03-18 00:00:00,2025-03-18 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68738,NaN,2025-03-19 00:00:00,2025-03-19 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68739,NaN,2025-03-20 00:00:00,2025-03-20 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
cols_to_convert = ['Lat', 'Lon', 'PM1', 'PM2.5', 'PM10']
for col in cols_to_convert:
    df[col] = df[col].str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [14]:
df['Time_Local'] = pd.to_datetime(df['Time_Local'], errors='coerce')

In [19]:
df

,Sensor,Time_UTC,Time_Local,Lat,Lon,PM1,PM2.5,PM10,NO2
0,I02,2021-01-01 00:00:00,2021-01-01 01:00:00,51.4379,5.3582,27.78,33.11,37.81,24.0
1,I02,2021-01-02 00:00:00,2021-01-02 01:00:00,51.4379,5.3582,31.84,45.09,51.59,19.0
2,I02,2021-01-03 00:00:00,2021-01-03 01:00:00,51.4379,5.3582,23.72,34.22,38.46,13.0
3,I02,2021-01-04 00:00:00,2021-01-04 01:00:00,51.4379,5.3582,5.35,5.97,7.94,9.0
4,I02,2021-01-05 00:00:00,2021-01-05 01:00:00,51.4379,5.3581,21.11,23.40,24.02,10.0
...,...,...,...,...,...,...,...,...,...
68735,NaN,2025-03-16 00:00:00,2025-03-16 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68736,NaN,2025-03-17 00:00:00,2025-03-17 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68737,NaN,2025-03-18 00:00:00,2025-03-18 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68738,NaN,2025-03-19 00:00:00,2025-03-19 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
68739,NaN,2025-03-20 00:00:00,2025-03-20 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.drop(columns=['Time_UTC'], inplace=True)

In [16]:
essential_cols = ['Sensor',  'PM1', 'PM2.5', 'PM10']
df.dropna(subset=essential_cols, inplace=True)

In [17]:
df.reset_index(drop=True, inplace=True)

In [18]:
grouped_df = df.groupby('Sensor').agg({
    'PM1': ['mean', 'median', 'std', 'min', 'max'],
    'PM2.5': ['mean', 'median', 'std', 'min', 'max'],
    'PM10': ['mean', 'median', 'std', 'min', 'max']
}).reset_index()

In [19]:
yearly_stats = []
for sensor, group in df.groupby('Sensor'):
    group = group.set_index('Time_Local')
    numeric_cols = group.select_dtypes(include='number').columns
    stats = group[numeric_cols].resample('YE').agg(['mean', 'median', 'std', 'min', 'max'])
    stats.columns = ['_'.join(col) for col in stats.columns]
    stats['Sensor'] = sensor
    yearly_stats.append(stats.reset_index())

yearly_stats_df = pd.concat(yearly_stats, ignore_index=True)

In [25]:
yearly_stats_df

,Time_Local,PM1_mean,PM1_median,PM1_std,PM1_min,PM1_max,PM2.5_mean,PM2.5_median,PM2.5_std,PM2.5_min,...,PM10_median,PM10_std,PM10_min,PM10_max,NO2_mean,NO2_median,NO2_std,NO2_min,NO2_max,Sensor
0,2022-12-31,9.156860,6.55,6.842175,3.03,33.37,12.257101,9.020,9.158179,4.09,...,19.81,10.688937,10.12,74.81,23.207729,22.0,10.183288,3.0,53.0,I01
1,2023-12-31,6.799699,5.17,5.052150,0.48,24.58,9.129397,7.180,6.153821,0.67,...,15.26,7.153786,3.49,45.41,12.167123,11.0,6.089715,2.0,38.0,I01
2,2024-12-31,7.021284,5.20,5.543151,1.03,33.19,9.285847,7.175,6.581801,1.60,...,14.09,7.434933,5.54,49.00,12.410959,11.0,6.382143,3.0,44.0,I01
3,2025-12-31,13.545949,10.49,9.330134,2.09,34.19,17.053671,14.020,11.746306,3.29,...,19.40,11.578704,6.97,58.18,20.620253,17.0,10.672639,5.0,49.0,I01
4,2021-12-31,12.842493,10.49,7.789723,0.77,35.42,15.666274,13.140,9.193143,1.41,...,18.74,9.643072,5.22,54.53,23.760870,20.0,13.121306,5.0,68.0,I02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,2025-12-31,13.298101,13.70,7.254333,0.95,24.36,17.048101,16.350,10.064476,1.78,...,21.80,12.222790,6.39,57.41,25.354430,27.0,9.046940,6.0,45.0,I62
235,2024-12-31,12.356667,8.52,8.100148,4.21,32.14,14.527333,12.370,8.657447,5.72,...,17.72,7.554285,8.76,41.05,12.000000,10.0,6.813851,5.0,30.0,I63
236,2025-12-31,17.548481,14.55,11.142634,2.81,40.56,20.782658,17.420,13.694785,3.81,...,23.14,13.689710,7.57,66.02,22.645570,21.0,11.518144,4.0,58.0,I63
237,2024-12-31,10.151333,7.63,6.092234,2.76,22.26,12.236667,9.580,6.924522,4.00,...,15.70,6.401919,8.58,35.10,16.200000,18.0,6.635403,7.0,27.0,I64
238,2025-12-31,13.644177,13.77,6.987401,2.07,24.55,17.029494,16.690,9.464113,2.78,...,21.80,11.297008,5.97,53.26,28.531646,29.0,10.390868,5.0,57.0,I64

In [ ]:
#yearly_stats_df.to_csv(f'{PATH_TO_DATASETS}merged_air_pollution_data_clean.csv', index=False)

In [23]:
air_pollution = pd.read_csv(f'{PATH_TO_DATASETS}merged_air_pollution_data_clean.csv')

In [24]:
air_pollution = air_pollution.dropna(subset=['Neighbourhood']).reset_index(drop=True)

In [5]:
neighbourhoods = pd.read_csv(f'{PATH_TO_DATASETS}Raw Datasets/buurten.csv', sep=';')

In [8]:
neighbourhoods

,BUURTCODE,BUURTNAAM,WIJKCODE,WIJKNAAM,STADSDEELCODE,STADSDEELNAAM,OBJECTID,OPPERVLAKTE,SHAPE.LEN,geo_shape,geo_point_2d
0,239,Leenderheide,23,Putten,2,Stadsdeel Stratum,657,1315094,6162.054696,"{""coordinates"": [[[5.511370601130445, 51.41529...","51.40871070914202, 5.510246313058235"
1,240,Riel,23,Putten,2,Stadsdeel Stratum,658,1283951,6359.183152,"{""coordinates"": [[[5.520271266523669, 51.42695...","51.41670116797133, 5.521552001267527"
2,532,Tempel,53,Aanschot,5,Stadsdeel Woensel-Noord,662,1190266,4525.443091,"{""coordinates"": [[[5.469716276375012, 51.48407...","51.48029692517017, 5.479872107812958"
3,523,Achtse Barrier-Spaaihoef,52,Achtse Molen,5,Stadsdeel Woensel-Noord,663,1015941,5252.710205,"{""coordinates"": [[[5.439586926395638, 51.48854...","51.48633901671497, 5.437133411484463"
4,543,Vaartbroek,54,Dommelbeemd,5,Stadsdeel Woensel-Noord,665,1011875,4300.438299,"{""coordinates"": [[[5.492520090952543, 51.48227...","51.478597626687694, 5.4986383772478105"
...,...,...,...,...,...,...,...,...,...,...,...
111,213,Elzent-Noord,21,Oud-Stratum,2,Stadsdeel Stratum,745,211974,1912.031719,"{""coordinates"": [[[5.484935423998946, 51.42964...","51.43102137706846, 5.48188073463311"
112,113,Witte Dame,11,Centrum,1,Stadsdeel Centrum,748,183780,1665.759571,"{""coordinates"": [[[5.469672232324015, 51.44168...","51.440389053412694, 5.472280423519718"
113,515,Winkelcentrum,51,Ontginning,5,Stadsdeel Woensel-Noord,751,177416,1695.314829,"{""coordinates"": [[[5.4786820169351484, 51.4678...","51.46932023444889, 5.475540025881163"
114,212,Rochusbuurt,21,Oud-Stratum,2,Stadsdeel Stratum,754,146625,1716.797826,"{""coordinates"": [[[5.493016993060386, 51.43220...","51.43210882505696, 5.48820270634632"
115,216,Bloemenplein,21,Oud-Stratum,2,Stadsdeel Stratum,756,133534,1695.060044,"{""coordinates"": [[[5.487913334889891, 51.42373...","51.42527141225692, 5.488570777411908"

In [7]:
neighbourhoods['WIJKNAAM'] = neighbourhoods['WIJKNAAM'].str.replace(r'\bWijk\b\s*', '', regex=True)

In [ ]:
wijk_to_buurt = neighbourhoods.groupby('WIJKNAAM')['BUURTNAAM'].first().to_dict()

air_pollution['Neighbourhood'] = air_pollution['Neighbourhood'].apply(
    lambda x: wijk_to_buurt[x] if x in wijk_to_buurt else x
)

In [10]:
air_pollution

,Time_Local,PM1_mean,PM1_median,PM1_std,PM1_min,PM1_max,PM2.5_mean,PM2.5_median,PM2.5_std,PM2.5_min,...,PM10_std,PM10_min,PM10_max,NO2_mean,NO2_median,NO2_std,NO2_min,NO2_max,Sensor,Neighbourhood
0,2022-12-31,9.156860,6.550,6.842175,3.03,33.37,12.257101,9.020,9.158179,4.09,...,10.688937,10.12,74.81,23.207729,22.0,10.183288,3.0,53.0,I01,Genderdal
1,2023-12-31,6.799699,5.170,5.052150,0.48,24.58,9.129397,7.180,6.153821,0.67,...,7.153786,3.49,45.41,12.167123,11.0,6.089715,2.0,38.0,I01,Genderdal
2,2024-12-31,7.021284,5.200,5.543151,1.03,33.19,9.285847,7.175,6.581801,1.60,...,7.434933,5.54,49.00,12.410959,11.0,6.382143,3.0,44.0,I01,Genderdal
3,2025-12-31,13.545949,10.490,9.330134,2.09,34.19,17.053671,14.020,11.746306,3.29,...,11.578704,6.97,58.18,20.620253,17.0,10.672639,5.0,49.0,I01,Genderdal
4,2021-12-31,12.842493,10.490,7.789723,0.77,35.42,15.666274,13.140,9.193143,1.41,...,9.643072,5.22,54.53,23.760870,20.0,13.121306,5.0,68.0,I02,Zandrijk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,2023-12-31,9.418669,6.620,7.470922,-0.16,33.91,11.685444,8.725,8.731133,0.12,...,10.065444,3.08,57.75,22.621302,21.0,10.869543,5.0,56.0,I40,Binnenstad
112,2024-12-31,7.684460,6.025,5.724707,0.38,29.49,9.655360,7.555,6.670928,0.85,...,7.222401,4.35,47.61,16.690647,15.0,8.684896,2.0,49.0,I40,Binnenstad
113,2025-12-31,16.007342,14.860,8.734498,2.57,29.84,19.937848,18.130,11.668863,3.72,...,12.616464,7.72,61.49,22.860759,23.0,10.068654,5.0,55.0,I40,Binnenstad
114,2024-12-31,9.519731,8.570,5.098820,1.13,24.72,11.619373,10.100,6.107339,2.06,...,6.919257,6.57,47.22,18.220896,17.0,7.044693,5.0,42.0,I59,Jagershoef
115,2025-12-31,13.554177,13.610,7.221898,2.55,25.48,17.534684,15.720,10.244262,3.43,...,11.580715,6.83,57.72,26.949367,27.0,10.268072,9.0,60.0,I59,Jagershoef

In [25]:
yearly_stats_df

,Time_Local,Lat_mean,Lat_median,Lat_std,Lat_min,Lat_max,Lon_mean,Lon_median,Lon_std,Lon_min,...,PM10_median,PM10_std,PM10_min,PM10_max,NO2_mean,NO2_median,NO2_std,NO2_min,NO2_max,Sensor
0,2022-12-31,51.406295,51.4063,0.000022,51.4062,51.4063,5.457386,5.4574,0.000035,5.4573,...,19.81,10.688937,10.12,74.81,23.207729,22.0,10.183288,3.0,53.0,I01
1,2023-12-31,51.406280,51.4063,0.000041,51.4061,51.4063,5.457352,5.4574,0.000050,5.4573,...,15.26,7.153786,3.49,45.41,12.167123,11.0,6.089715,2.0,38.0,I01
2,2024-12-31,51.406271,51.4063,0.000045,51.4062,51.4063,5.457378,5.4574,0.000042,5.4573,...,14.09,7.434933,5.54,49.00,12.410959,11.0,6.382143,3.0,44.0,I01
3,2025-12-31,51.406291,51.4063,0.000029,51.4062,51.4063,5.457383,5.4574,0.000038,5.4573,...,19.40,11.578704,6.97,58.18,20.620253,17.0,10.672639,5.0,49.0,I01
4,2021-12-31,51.437900,51.4379,0.000000,51.4379,51.4379,5.358149,5.3581,0.000050,5.3581,...,18.74,9.643072,5.22,54.53,23.760870,20.0,13.121306,5.0,68.0,I02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,2025-12-31,51.358097,51.3581,0.000016,51.3580,51.3581,5.317897,5.3179,0.000023,5.3177,...,21.80,12.222790,6.39,57.41,25.354430,27.0,9.046940,6.0,45.0,I62
235,2024-12-31,51.359100,51.3591,0.000000,51.3591,51.3591,5.332000,5.3320,0.000000,5.3320,...,17.72,7.554285,8.76,41.05,12.000000,10.0,6.813851,5.0,30.0,I63
236,2025-12-31,51.359097,51.3591,0.000016,51.3590,51.3591,5.332003,5.3320,0.000016,5.3320,...,23.14,13.689710,7.57,66.02,22.645570,21.0,11.518144,4.0,58.0,I63
237,2024-12-31,51.373800,51.3738,0.000000,51.3738,51.3738,5.354100,5.3541,0.000000,5.3541,...,15.70,6.401919,8.58,35.10,16.200000,18.0,6.635403,7.0,27.0,I64
238,2025-12-31,51.373844,51.3738,0.000050,51.3738,51.3739,5.354096,5.3541,0.000019,5.3540,...,21.80,11.297008,5.97,53.26,28.531646,29.0,10.390868,5.0,57.0,I64

In [26]:
sensor_to_lat = yearly_stats_df.groupby('Sensor')['Lat_mean'].first().to_dict()
sensor_to_lon = yearly_stats_df.groupby('Sensor')['Lon_mean'].first().to_dict()

air_pollution['LAT'] = air_pollution['Sensor'].map(sensor_to_lat)
air_pollution['LON'] = air_pollution['Sensor'].map(sensor_to_lon)

In [27]:
air_pollution.to_csv(f'{PATH_TO_DATASETS}merged_air_pollution_data_clean.csv', index=False)